apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: {{ .Values.myapp.image }}
        ports:
        - containerPort: 8080
        # env:
        # - name: user
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: usernameh
        # - name: password
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: password
        # - name: db
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: db